from enum import StrEnum

TMP_DIRPATH = "tmp/"

ASSET_DIRPATH = "asset/"

MOD_DIRPATH = "mod/"


class KnownTable(StrEnum):
    ACTIVITY_TABLE = "activity_table"
    AUDIO_DATA = "audio_data"
    BATTLE_EQUIP_TABLE = "battle_equip_table"
    BUFF_TABLE = "buff_table"
    BUILDING_DATA = "building_data"
    BUILDING_LOCAL_DATA = "building_local_data"
    CAMPAIGN_TABLE = "campaign_table"
    CHAPTER_TABLE = "chapter_table"
    CHARACTER_TABLE = "character_table"
    CHARM_TABLE = "charm_table"
    CHARWORD_TABLE = "charword_table"
    CHAR_MASTER_TABLE = "char_master_table"
    CHAR_META_TABLE = "char_meta_table"
    CHAR_PATCH_TABLE = "char_patch_table"
    CHECKIN_TABLE = "checkin_table"
    CLIMB_TOWER_TABLE = "climb_tower_table"
    CLUE_DATA = "clue_data"
    COOPERATE_BATTLE_TABLE = "cooperate_battle_table"
    CRISIS_TABLE = "crisis_table"
    CRISIS_V2_TABLE = "crisis_v2_table"
    DISPLAY_META_TABLE = "display_meta_table"
    ENEMY_DATABASE = "enemy_database"
    ENEMY_HANDBOOK_TABLE = "enemy_handbook_table"
    EP_BREAKBUFF_TABLE = "ep_breakbuff_table"
    EXTRA_BATTLELOG_TABLE = "extra_battlelog_table"
    FAVOR_TABLE = "favor_table"
    GACHA_TABLE = "gacha_table"
    GAMEDATA_CONST = "gamedata_const"
    HANDBOOK_INFO_TABLE = "handbook_info_table"
    HANDBOOK_TEAM_TABLE = "handbook_team_table"
    HOTUPDATE_META_TABLE = "hotupdate_meta_table"
    INIT_TEXT = "init_text"
    ITEM_TABLE = "item_table"
    LEGION_MODE_BUFF_TABLE = "legion_mode_buff_table"
    LEVEL_SCRIPT_TABLE = "level_script_table"
    MAIN_TEXT = "main_text"
    MEDAL_TABLE = "medal_table"
    META_UI_TABLE = "meta_ui_table"
    MISSION_TABLE = "mission_table"
    OPEN_SERVER_TABLE = "open_server_table"
    REPLICATE_TABLE = "replicate_table"
    RETRO_TABLE = "retro_table"
    ROGUELIKE_TOPIC_TABLE = "roguelike_topic_table"
    SANDBOX_PERM_TABLE = "sandbox_perm_table"
    SHOP_CLIENT_TABLE = "shop_client_table"
    SKILL_TABLE = "skill_table"
    SKIN_TABLE = "skin_table"
    SPECIAL_OPERATOR_TABLE = "special_operator_table"
    STAGE_TABLE = "stage_table"
    STORY_REVIEW_META_TABLE = "story_review_meta_table"
    STORY_REVIEW_TABLE = "story_review_table"
    STORY_TABLE = "story_table"
    TIP_TABLE = "tip_table"
    TOKEN_TABLE = "token_table"
    UNIEQUIP_TABLE = "uniequip_table"
    ZONE_TABLE = "zone_table"

    HANDBOOK_TABLE = "handbook_table"
    PLAYER_AVATAR_TABLE = "player_avatar_table"
    RANGE_TABLE = "range_table"
    ROGUELIKE_TABLE = "roguelike_table"
    SANDBOX_TABLE = "sandbox_table"
    TECH_BUFF_TABLE = "tech_buff_table"
    UNIEQUIP_DATA = "uniequip_data"

    BATTLE_MISC_TABLE = "battle_misc_table"

    BUFF_TEMPLATE_DATA = "buff_template_data"

    DATA_VERSION = "data_version"
